##FREE IPA
docker pull freeipa/freeipa-server:almalinux-8-4.9.13
docker save -o freeipa_almalinux.tar 863c059e8d4a freeipa_almalinux:8-4.9.13

# namespace remapping for the container cgroup #/etc/docker/daemon.json
$ sudo sh -c 'touch /etc/docker/daemon.json && echo "{ \"userns-remap\": \"default\" }" >> /etc/docker/daemon.json'

sudo systemctl restart docker

# sysmtemd services
setsebool -P container_manage_cgroup 1

#free ipa data
mkdir /var/lib/ipa-data

#1 FreeIPA container
sudo docker run --name freeipa-server1 -ti -h station1.lk.example.com --read-only -v /home/sam/ipa-data:/data:Z 863c059e8d4a

# 2 DNS server 
docker run -ti -h station1.lk.example.com --read-only -v /home/sam/ipa-data:/data:Z -e PASSWORD=Secret123 863c059e8d4a ipa-server-install -U -r STATION1.LK.EXAMPLE.COM --no-ntp

sudo firewall-cmd --zone=public --add-port=80/tcp --add-port=443/tcp --add-port=389/tcp --add-port=636/tcp --add-port=88/tcp --add-port=464/tcp --add-port=88/udp --add-port=464/udp --permanent
sudo firewall-cmd --reload

ipa-server-install